version: '3'
services:
  web:
    build: .
    command: uvicorn deploy:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      custom_net:
        ipv4_address: 10.5.0.5

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16